# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0659
  location: westus

  environment: dev
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps 
  ado_service_connection_rg: Azure-ARM-Dev-murggu
  ado_service_connection_aml_ws: Azure-ARM-Dev

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment) 
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure/terraform
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
